/*
 * deposits/transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;
import cores.model.RestError;

/**
 * ErrorResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-05T04:37:43.742Z")
public class ErrorResponse {
	@SerializedName("errors")
	private List<RestError> errors = null;
	
//	private long time = new Date().getTime();
//	
//
//	public long getTime() {
//		return time;
//	}
//
//	public void setTime(long time) {
//		this.time = time;
//	}

	public ErrorResponse errors(List<RestError> errors) {
		this.errors = errors;
		return this;
	}

	public ErrorResponse addErrorsItem(RestError errorsItem) {
		if (this.errors == null) {
			this.errors = new ArrayList<RestError>();
		}
		this.errors.add(errorsItem);
		return this;
	}

	public ErrorResponse addErrorsItem(MambuError errorMambu) {
		return addErrorsItem(new RestError(errorMambu));
	}

	/**
	 * Get errors
	 * 
	 * @return errors
	 **/
	@ApiModelProperty(value = "")
	public List<RestError> getErrors() {
		return errors;
	}
	
	public void setErrors(List<RestError> errors) {
		this.errors = errors;
	}

	public ErrorResponse() {
		super();
	}
	public ErrorResponse(MambuError error) {
		super();
		addErrorsItem(error);
	}
	public ErrorResponse(RestError error) {
		super();
		addErrorsItem(error);
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ErrorResponse errorResponse = (ErrorResponse) o;
		return Objects.equals(this.errors, errorResponse.errors);
	}

	@Override
	public int hashCode() {
		return Objects.hash(errors);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ErrorResponse {\n");

		sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
