spring:
  cloud:
    gateway:
      routes:
        - id: service-customer
          uri: http://localhost:8081/
          predicates:
            - Path=/service-customer/**
        - id: service-health
          uri: http://localhost:8080/
          predicates:
            - Path=/service-health/**
  application:
    name: Edge server

eureka:
  client:
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761
  instance:
    hostname: localhost
server:
  port: 8765
